# Multiple Web Scraper Tools Configuration
# This file demonstrates how to configure multiple web scraper instances

source:
  source_id: "web_scrapers_config"
  description: "Multiple web scraper tools from different MCP servers"

tools:
  - tool_id: "crawl4ai_primary"
    tool_type: "web_scraper"
    name: "Primary Crawl4AI Scraper"
    description: "Main web scraper using Crawl4AI MCP server"
    enabled: false  # Disabled - demo tool, enable if needed
    config:
      mcp_server_url: "https://primary-crawl4ai.company.com"
      api_key: "${CRAWL4AI_PRIMARY_API_KEY}"
    tags: ["primary", "web_scraping", "production"]
    priority: 10

  - tool_id: "crawl4ai_backup"
    tool_type: "web_scraper"
    name: "Backup Crawl4AI Scraper"
    description: "Backup web scraper for failover scenarios"
    enabled: false  # Disabled - demo tool, enable if needed
    config:
      mcp_server_url: "https://backup-crawl4ai.company.com"
      api_key: "${CRAWL4AI_BACKUP_API_KEY}"
    tags: ["backup", "web_scraping", "failover"]
    priority: 5

  - tool_id: "specialized_news_scraper"
    tool_type: "web_scraper"
    name: "News-Specialized Scraper"
    description: "Specialized scraper optimized for news websites"
    enabled: false  # Disabled - demo tool, enable if needed
    config:
      mcp_server_url: "https://news-scraper.company.com"
      api_key: "${NEWS_SCRAPER_API_KEY}"
    tags: ["news", "specialized", "media"]
    priority: 8

  - tool_id: "ecommerce_scraper"
    tool_type: "web_scraper"
    name: "E-commerce Scraper"
    description: "Specialized scraper for e-commerce product pages"
    enabled: false  # Disabled - demo tool, enable if needed
    config:
      mcp_server_url: "https://ecommerce-scraper.company.com"
      api_key: "${ECOMMERCE_SCRAPER_API_KEY}"
    tags: ["ecommerce", "products", "specialized"]
    priority: 7

  - tool_id: "development_scraper"
    tool_type: "web_scraper"
    name: "Development Scraper"
    description: "Development environment scraper for testing"
    enabled: false  # Disabled in production
    config:
      mcp_server_url: "https://dev-crawl4ai.company.com"
      api_key: "${DEV_SCRAPER_API_KEY}"
    tags: ["development", "testing", "dev"]
    priority: 1
