# Advanced GCP Environment Intelligence Configuration
# Multi-agent setup for comprehensive infrastructure management

version: "1.0"

# Specialized agents for different aspects of GCP management
agents:
  # Primary infrastructure optimizer
  - id: gcp_optimizer
    name: "GCP Infrastructure Optimizer"
    model: "gpt-4o"
    behavior: |
      You are an expert Google Cloud Platform infrastructure optimizer with deep knowledge
      of GCP services, pricing, and best practices. Your role is to analyze environments
      and provide comprehensive optimization recommendations.
      
      Expertise Areas:
      - Multi-service cost optimization strategies
      - Performance tuning and scaling optimization
      - Resource allocation and utilization analysis
      - Architecture review and modernization recommendations
      
      Approach:
      1. Perform comprehensive environment analysis
      2. Identify optimization opportunities across all dimensions
      3. Prioritize recommendations by business impact and ROI
      4. Provide detailed implementation roadmaps
    
    tools:
      - id: gcp_env
        type: mcpgcp_environment
        local_mode: true
    
    memory: production

  # Security specialist
  - id: security_advisor
    name: "GCP Security Advisor"
    model: "gpt-4o"
    behavior: |
      You are a Google Cloud Platform security specialist focused on cloud security 
      posture, compliance, and risk management. You assess security configurations
      and provide actionable security improvement recommendations.
      
      Security Focus:
      - IAM permissions and least-privilege implementation
      - Network security and firewall optimization
      - Data protection and encryption strategies
      - Compliance framework alignment (SOC2, GDPR, HIPAA)
      - Security monitoring and incident response
      
      Risk Assessment:
      - Classify findings by severity and business impact
      - Provide cost-benefit analysis for security investments
      - Include compliance deadlines and regulatory requirements
      - Design security automation and monitoring strategies
    
    tools:
      - id: gcp_env
        type: mcpgcp_environment
        local_mode: true
    
    memory: production

  # Cost optimization specialist
  - id: cost_controller
    name: "GCP Cost Controller"
    model: "gpt-4o"
    behavior: |
      You are a Google Cloud Platform cost optimization expert specializing in
      cloud financial management and cost efficiency optimization.
      
      Financial Expertise:
      - Cost analysis and trend forecasting
      - Resource right-sizing and optimization
      - Reserved instance and commitment recommendations
      - Billing optimization and cost allocation strategies
      
      Business Focus:
      - ROI analysis for optimization investments
      - Cost-performance trade-off optimization
      - Budget planning and variance analysis
      - Chargeback and showback implementation
    
    tools:
      - id: gcp_env
        type: mcpgcp_environment
        local_mode: true
    
    memory: production

  # Performance monitoring specialist
  - id: performance_monitor
    name: "GCP Performance Monitor"
    model: "gpt-4o"
    behavior: |
      You are a Google Cloud Platform performance monitoring and optimization expert
      focused on application performance, infrastructure efficiency, and user experience.
      
      Performance Areas:
      - Application performance monitoring and optimization
      - Infrastructure utilization and scaling strategies
      - Latency optimization and throughput improvement
      - SLA/SLO monitoring and alerting design
      
      Optimization Strategy:
      - Establish performance baselines and KPIs
      - Identify bottlenecks and performance constraints
      - Design auto-scaling and load balancing strategies
      - Implement comprehensive monitoring and alerting
    
    tools:
      - id: gcp_env
        type: mcpgcp_environment
        local_mode: true
    
    memory: production

# Comprehensive workflows for different optimization scenarios
workflows:
  # Complete infrastructure assessment
  - id: complete_gcp_assessment
    name: "Complete GCP Infrastructure Assessment"
    description: "Comprehensive multi-agent analysis of GCP environment"
    
    steps:
      - id: environment_overview
        agent: gcp_optimizer
        input: |
          Provide a comprehensive overview of our current GCP environment including:
          - Platform and deployment architecture
          - Resource inventory and utilization
          - Current configuration and setup analysis
        
      - id: cost_deep_dive
        agent: cost_controller
        input: |
          Perform detailed cost analysis including:
          - Current spending breakdown by service
          - Cost trends and forecasting
          - Optimization opportunities with savings estimates
          - Budget recommendations and variance analysis
        depends_on: [environment_overview]
        
      - id: security_assessment
        agent: security_advisor
        input: |
          Conduct comprehensive security assessment including:
          - IAM permissions audit and recommendations
          - Security posture evaluation
          - Compliance status and gap analysis
          - Risk prioritization and remediation roadmap
        depends_on: [environment_overview]
        
      - id: performance_analysis
        agent: performance_monitor
        input: |
          Analyze performance metrics and optimization opportunities:
          - Current performance baseline establishment
          - Bottleneck identification and impact analysis
          - Scaling strategy recommendations
          - Monitoring and alerting optimization
        depends_on: [environment_overview]
        
      - id: optimization_roadmap
        agent: gcp_optimizer
        input: |
          Based on all previous analyses, create a comprehensive optimization roadmap:
          - Prioritized recommendations across cost, security, and performance
          - Implementation timeline with dependencies
          - Success metrics and measurement strategies
          - Risk assessment and mitigation plans
        depends_on: [cost_deep_dive, security_assessment, performance_analysis]

  # Focused cost optimization workflow
  - id: cost_optimization_sprint
    name: "GCP Cost Optimization Sprint"
    description: "Intensive cost reduction analysis and implementation plan"
    
    steps:
      - id: cost_baseline
        agent: cost_controller
        input: |
          Establish comprehensive cost baseline:
          - Current month spending analysis
          - Year-over-year cost trends
          - Service-level cost breakdown
          - Peak spending identification
        
      - id: resource_efficiency
        agent: gcp_optimizer
        input: |
          Analyze resource efficiency and utilization:
          - Underutilized resource identification
          - Right-sizing opportunities
          - Scheduling and automation potential
          - Architecture optimization possibilities
        depends_on: [cost_baseline]
        
      - id: savings_opportunities
        agent: cost_controller
        input: |
          Identify and quantify savings opportunities:
          - Immediate cost reduction actions
          - Medium-term optimization projects
          - Long-term strategic initiatives
          - Risk-adjusted savings projections
        depends_on: [resource_efficiency]
        
      - id: implementation_plan
        agent: cost_controller
        input: |
          Create detailed cost optimization implementation plan:
          - 30-60-90 day action items
          - Resource requirements and dependencies
          - Success metrics and tracking methods
          - Change management and risk mitigation
        depends_on: [savings_opportunities]

  # Security hardening workflow
  - id: security_hardening_sprint
    name: "GCP Security Hardening Sprint"
    description: "Comprehensive security assessment and improvement plan"
    
    steps:
      - id: security_posture_assessment
        agent: security_advisor
        input: |
          Conduct thorough security posture assessment:
          - Current security configuration analysis
          - Vulnerability identification and classification
          - Compliance gap analysis
          - Risk exposure evaluation
        
      - id: threat_modeling
        agent: security_advisor
        input: |
          Perform threat modeling and risk analysis:
          - Attack surface identification
          - Threat vector analysis
          - Impact assessment for identified risks
          - Risk prioritization matrix
        depends_on: [security_posture_assessment]
        
      - id: security_roadmap
        agent: security_advisor
        input: |
          Develop comprehensive security improvement roadmap:
          - Critical security fixes (immediate)
          - Security enhancement projects (short-term)
          - Strategic security initiatives (long-term)
          - Compliance achievement timeline
        depends_on: [threat_modeling]
        
      - id: security_automation
        agent: security_advisor
        input: |
          Design security automation and monitoring strategy:
          - Automated security scanning and assessment
          - Real-time monitoring and alerting
          - Incident response automation
          - Continuous compliance monitoring
        depends_on: [security_roadmap]

  # Performance optimization workflow
  - id: performance_optimization_sprint
    name: "GCP Performance Optimization Sprint"
    description: "Performance analysis and optimization implementation"
    
    steps:
      - id: performance_baseline
        agent: performance_monitor
        input: |
          Establish comprehensive performance baseline:
          - Current performance metrics analysis
          - Historical performance trends
          - Performance SLA/SLO evaluation
          - Bottleneck identification
        
      - id: optimization_analysis
        agent: performance_monitor
        input: |
          Analyze performance optimization opportunities:
          - Resource scaling optimization
          - Application performance tuning
          - Network and I/O optimization
          - Caching and data optimization
        depends_on: [performance_baseline]
        
      - id: scaling_strategy
        agent: performance_monitor
        input: |
          Design optimal scaling and load management strategy:
          - Auto-scaling policy optimization
          - Load balancing configuration
          - Traffic routing optimization
          - Capacity planning recommendations
        depends_on: [optimization_analysis]
        
      - id: monitoring_enhancement
        agent: performance_monitor
        input: |
          Design enhanced monitoring and alerting strategy:
          - Key performance indicator definition
          - Real-time monitoring dashboard design
          - Proactive alerting configuration
          - Performance regression detection
        depends_on: [scaling_strategy]

# Advanced tools configuration
tools:
  - id: gcp_env
    type: mcpgcp_environment
    local_mode: true
    settings:
      # Comprehensive analysis settings
      include_costs: true
      include_security: true
      include_performance: true
      include_recommendations: true
      
      # Extended analysis parameters
      metrics_period_hours: 168  # 1 week of metrics
      include_historical_trends: true
      cost_forecast_months: 12
      include_service_breakdown: true
      
      # Security assessment settings
      compliance_frameworks: ["SOC2", "GDPR", "HIPAA", "PCI-DSS"]
      security_scan_depth: "comprehensive"
      include_vulnerability_assessment: true
      
      # Performance monitoring settings
      performance_threshold_cpu: 80
      performance_threshold_memory: 85
      performance_threshold_latency: 500
      include_application_metrics: true

# Memory configuration for persistent learning
memory:
  type: production
  settings:
    # Use BigQuery for comprehensive analysis storage
    adapter_type: "bigquery"
    
    # Retention for optimization learning
    retention_policy:
      analysis_results: "1 year"
      optimization_recommendations: "2 years"
      implementation_feedback: "indefinite"

# Session configuration for multi-agent coordination
session:
  strategy: "hybrid"
  scoping: "workflow-scoped"
  settings:
    sharing_strategy: "full_context"
    context_window_management: "dynamic"
    cross_agent_memory: true