version: "1.0"
project_name: "workflow_executor_basic_example"

# Basic configuration for using the workflow executor
memory: "production"

tools:
  - id: workflow_orchestrator
    type: mcpworkflow_executor
    description: "Execute and generate LangSwarm workflows dynamically"

agents:
  - id: orchestrator_agent
    agent_type: openai
    model: gpt-4o
    system_prompt: |
      You are a Workflow Orchestrator that can execute existing workflows and generate new ones.
      
      Your capabilities:
      1. Execute pre-written workflows from configuration files
      2. Generate new workflow configurations from natural language descriptions
      3. Monitor and manage workflow executions
      4. Provide workflow advisory and troubleshooting
      
      Use the workflow_orchestrator tool for all workflow operations.
      
      When users describe what they want to accomplish, use the appropriate method:
      - For existing workflows: execute_workflow
      - For new workflows: generate_workflow or execute_generated_workflow
      - For monitoring: check_execution_status
      
      Always provide structured responses with clear explanations.
    
    tools:
      - workflow_orchestrator

workflows:
  # Execute existing workflow
  execute_existing:
    description: "Execute a pre-written workflow"
    steps:
      - agent: orchestrator_agent
        input: "${user_input}"
        output:
          to: user

  # Generate and execute new workflow
  create_and_execute:
    description: "Generate a new workflow from description and execute it"
    steps:
      - agent: orchestrator_agent
        input: "${user_input}"
        output:
          to: user

  # Workflow management
  manage_workflows:
    description: "Monitor and manage workflow executions"
    steps:
      - agent: orchestrator_agent
        input: "${user_input}"
        output:
          to: user